Repository 24seconds/rust-cli-pomodoro, pull requests merged in 2022-05, with the labels that each got.

#55 Support ipc
  Cargo.lock
  Cargo.toml
  src/argument.rs
  src/command/action.rs
  src/command/application.rs
  src/command/handler/mod.rs
  src/command/handler/uds_client.rs
  src/command/handler/user_input.rs
  src/command/mod.rs
  src/command/output.rs
  src/command/util.rs
  src/configuration.rs
  src/input_handler.rs
  src/ipc.rs
  src/main.rs
  src/notification/archived_notification.rs
  src/notification/mod.rs
  src/notification/notify.rs
  src/report.rs
Labels: enhancement

#62 Modify checkbox uses in README.md
  README.md
Labels: documentation

#66 Fix bug: IPC command delete not work
  src/command/application.rs
  src/ipc.rs
Labels: bug

#68 Implement pingpong to respect already running pomodoro for ipc
  src/command/handler/uds_client.rs
  src/ipc.rs
  src/main.rs
  src/notification/archived_notification.rs
Labels: bug, enhancement
