Repository 24seconds/rust-cli-pomodoro, pull requests merged in 2023-03, with the labels that each got.

#147 Added auto-completion for shells
  Cargo.lock
  Cargo.toml
  src/command/application.rs
  src/command/util.rs
  src/main.rs
Labels: enhancement

#149 fix cargo clippy, cargo test
  src/command/application.rs
  src/command/handler/user_input.rs
  src/error.rs
  src/ipc.rs
  src/main.rs
  src/notification/archived_notification.rs
  src/notification/mod.rs
Labels: bug

#151 Added rustyline support for arrow keys + more
  Cargo.lock
  Cargo.toml
  src/command/util.rs
  src/line_handler.rs
  src/main.rs
Labels: enhancement

#153 update version to v1.3.4
  Cargo.lock
  Cargo.toml
Labels: deployment

#154 Upgrade clap and clap_complete version
  Cargo.lock
  Cargo.toml
  src/command/action.rs
  src/command/application.rs
  src/command/handler/uds_client.rs
  src/command/handler/user_input.rs
  src/command/util.rs
  src/configuration.rs
  src/error.rs
  src/main.rs
Labels: dependencies

#158 separate a job for `cargo test`
  .github/workflows/rust.yml
Labels: enhancement

#161 Update tabled version from 0.8.0 -> 0.10.0
  Cargo.lock
  Cargo.toml
  src/command/handler/user_input.rs
  src/notification/archived_notification.rs
  src/notification/mod.rs
Labels: dependencies
