Repository 24seconds/rust-cli-pomodoro, pull requests merged in 2023-04, with the labels that each got.

#165 Add Percentage column with list
  src/command/application.rs
  src/command/handler/user_input.rs
  src/command/util.rs
  src/configuration.rs
  src/notification/mod.rs
Labels: enhancement

#166 Issue 163 fix d a command bug
  src/command/application.rs
Labels: bug

#173 Introduce table driven test cases
  src/notification/mod.rs
Labels: enhancement

#174 Change action: Build -> Check
  .github/workflows/rust.yml
Labels: enhancement

#175 Add clear history feature
  src/command/application.rs
  src/command/handler/user_input.rs
  src/database.rs
Labels: enhancement

#176 Prepare v1.4.0 release
  .gitignore
  Cargo.lock
  Cargo.toml
  README.md
  assets/auto_completion_example.png
Labels: documentation, deployment

#178 support list -p in ipc mode
  src/command/handler/uds_client.rs
  src/ipc.rs
Labels: enhancement

#179 update version v1.4.1
  Cargo.lock
  Cargo.toml
Labels: deployment

#183 prepare v1.4.2
  Cargo.lock
  Cargo.toml
Labels: deployment

#185 Fix create and queue not working with 1 param in IPC mode
  src/command/handler/uds_client.rs
  src/command/util.rs
  src/ipc.rs
  src/main.rs
  src/notification/mod.rs
Labels: bug

#188 update version to 1.4.3
  Cargo.lock
  Cargo.toml
Labels: deployment
